version: '3.7'
services:
    fpm:
        container_name: projetS4-fpm
        build: ./services/fpm/
        environment:
            SSH_AUTH_SOCK: /auth.sock
            PHP_IDE_CONFIG: serverName=localhost
        volumes:
            - ./app:/var/www/html:cached
    nginx:
        container_name: projetS4-nginx
        image: nginx:1.15.5
        volumes:
            - ./app:/var/www/html:cached
            - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"
